services:
  envoy:
    image: envoy-with-dynamic-modules:latest
    container_name: envoy
    ports:
      - "1062:1062"
      - "1063:1063"
      - "1064:1064"
    volumes:
      - ./:/examples
    working_dir: /examples/integration
    command: ["/bin/sh", "-c", "mkdir -p ./access_logs && envoy --config-path ./envoy.yaml"]
    networks:
      - envoy-net

  echo:
    image: hashicorp/http-echo
    depends_on:
      - envoy
    network_mode: "container:envoy"
    command:
      - "-listen=127.0.0.1:1234"
      - "-text=Hello from echo server"

networks:
  envoy-net:
    driver: bridge
